- rustfmt.toml
- src/mainboard/emulation/qemu-armv7/src/main.rs
- src/mainboard/emulation/qemu-armv7/src/romstage.rs
This is all still experimental.
We need a device model, I will propose one in the next day or so.
I like the use of mod since it fixes the coreboot problem of inadvertently
calling one stage from another.
> Add a romstage file

- src/mainboard/emulation/qemu-armv7/src/main.rs
- src/mainboard/emulation/qemu-armv7/src/print.rs
We won't buffer and the impl for writeto will do a polled write to uart with a timeout.
working print!
> Figuring out standalone printing

- payloads/payload/serialize.rs
> cbfs serialize WIP

- README.md
Need to set default toolchain to nightly.
> add one missing command to the doc

- README.md
> Add more steps to installation instructions

- drivers/src/uart/pl011.rs
Sets baud rate registers based on the table given in the PL011 manual.
> Adding baud rate calculation

- src/mainboard/ast/ast25x0/src/main.rs
- src/mainboard/ast/ast25x0/src/vector_table.S
> Add correct UART bases for ast2500

- src/mainboard/ast/ast25x0/src/romstage/asmram.rs
- src/mainboard/ast/ast25x0/src/romstage/asmram/ram.rs
I did not removed the lines. This makes it a bit easier as we move on
to line up old warning messages with the changes.
> Get rid of the warnings.

- src/mainboard/ast/ast25x0/src/main.rs
- src/mainboard/ast/ast25x0/src/romstage/asmram.rs
This is a bare minimum setup state. No magic numbers allowed.
> Add a state for uart setup

- src/mainboard/ast/ast25x0/src/main.rs
- src/mainboard/ast/ast25x0/src/print.rs
> The dyn Trait feature is the new syntax for using trait objects

- src/mainboard/ast/ast25x0/Makefile.toml
- src/mainboard/ast/ast25x0/src/vector_table.S
> Load the AST250 ROM into address 0x0 in QEMU

- src/mainboard/ast/ast25x0/Cargo.toml
- src/mainboard/emulation/qemu-armv7/Cargo.toml
> Enable link-time-optimization

- README.md
> Add asciinema demo

- .gitlab-ci.yml
> ci: Fix invalid config

- .gitlab-ci.yml
> ci: Temporarily remove clippy

- src/arch/arm/armv7/Cargo.toml
- src/arch/arm/armv7/src/lib.rs
- src/arch/arm/armv7/src/mmu.S
- src/mainboard/ast/ast25x0/Cargo.lock
- src/mainboard/ast/ast25x0/Cargo.toml
- src/mainboard/ast/ast25x0/Makefile.toml
- src/mainboard/ast/ast25x0/src/main.rs
- src/mainboard/ast/ast25x0/src/romstage/asmram.rs
it does nothing yet but it's way cleaner to do this than add a
coprocessor device, which was my first idea.
> Add an mmu driver

- README.md
> Add instructions to build QEMU from source

- src/mainboard/sifive/hifive/Makefile.toml
Signed-off-by: Gan Shun Lim <ganshun@gmail.com>
> Change run instructions for riscv

- src/mainboard/sifive/hifive/link.ld
Also remove incorrect ARM lines.
Signed-off-by: Gan Shun Lim <ganshun@gmail.com>
> New link location for riscv

- src/arch/riscv/rv64/src/bootblock.S
- src/arch/riscv/rv64/src/reg.rs
- src/mainboard/sifive/hifive/Makefile.toml
> uncomment most of the bootblock.

- src/mainboard/sifive/hifive/Makefile.toml
> remove the step intended to chop off the first 2G of zeros

- azure-pipelines.yml
> Add starter pipeline

- src/drivers/uart/src/log.rs
- src/drivers/uart/src/sifive.rs
- src/mainboard/sifive/hifive/src/main.rs
- src/soc/sifive/fu540/src/reg.rs
> Fix compiler warnings

- azure-pipelines.yml
> Build for Risc-V in CI

- README.md
- azure-pipelines.yml
- src/mainboard/sifive/hifive/Makefile.toml
- src/mainboard/sifive/hifive/src/main.rs
This simply checks that the string TESTTESTTEST is printed. This is
fairly basic and we can setup some more sophisticated in the future.
> Add QEMU CI test for RISC-V

- azure-pipelines.yml
> Perform nightly build to catch breakages

- tools/soc/sifive/fu540/Makefile
- tools/soc/sifive/fu540/serialdebug.S
> Add RISCV serial debug tool

- tools/soc/sifive/fu540/Makefile
- tools/soc/sifive/fu540/link.ld
- tools/soc/sifive/fu540/serialdebug.S
> Add RISCV serial debug tool, part 2

- tools/soc/sifive/fu540/Makefile
> fu540 serialtool: add makefile clauses for ROM creation

- tools/soc/sifive/fu540/Makefile
- tools/soc/sifive/fu540/serialdebug.S
- tools/soc/sifive/fu540/uart-qemu.diff
> Add QEMU UART patch

- azure-pipelines.yml
- src/mainboard/sifive/hifive/src/main.rs
> Use correct UART addresses in driver and CI

- payloads/Cargo.toml
- src/arch/arm/armv7/Cargo.toml
- src/arch/riscv/rv64/Cargo.toml
- src/console/Cargo.toml
- src/cpu/armltd/cortex-a9/Cargo.toml
- src/drivers/clock/Cargo.toml
- src/drivers/model/Cargo.toml
- src/drivers/sifive/spi/Cargo.toml
- src/drivers/uart/Cargo.toml
- src/drivers/wrappers/Cargo.toml
- src/lib/device_tree/Cargo.toml
- src/mainboard/ast/ast25x0/Cargo.toml
- src/mainboard/emulation/qemu-armv7/Cargo.toml
- src/mainboard/sifive/hifive/Cargo.toml
- src/soc/aspeed/ast2500/Cargo.toml
- src/soc/sifive/fu540/Cargo.toml
> Change all authors to 'Oreboot Authors'

- azure-pipelines.yml
- src/mainboard/sifive/hifive/Makefile.toml
- src/mainboard/sifive/hifive/src/main.rs
- src/soc/sifive/fu540/src/clock.rs
- src/soc/sifive/fu540/src/ddr.rs
- src/soc/sifive/fu540/src/reg.rs
- src/soc/sifive/fu540/src/ux00.rs
Signed-off-by: Gan Shun Lim <ganshun@gmail.com>
> Fix up ddr code to actually turn on DRAM

- Documentation/sifive/setup.md
> Update documenation with layoutflash tool

- src/drivers/uart/src/ns16550.rs
> drivers/uart/ns16550: Tidy up whitespace

- Documentation/sifive/setup.md
> Add documentation to run gdb on hardware

- src/mainboard/sifive/hifive/src/main.rs
Signed-off-by: Philipp Hug <philipp@hug.cx>
> hifive-u: use same payload for qemu and hardware

- .github/auto-merge.yml
Docs for this tool: https://github.com/bobvanderlinden/probot-auto-merge
> Auto merge pull requests with the 'merge' tag

- src/mainboard/emulation/qemu-armv7/src/main.rs
> Made more writes idiomatic

- src/mainboard/nuvoton/npcm7xx/Cargo.toml
- src/mainboard/nuvoton/npcm7xx/Makefile.toml
- src/mainboard/nuvoton/npcm7xx/README
- src/mainboard/nuvoton/npcm7xx/build.rs
- src/mainboard/nuvoton/npcm7xx/fixed-dtfs.dts
- src/mainboard/nuvoton/npcm7xx/link.ld
- src/mainboard/nuvoton/npcm7xx/src/main.rs
build fails for reasons I don't understand.
> npcm7xx skeleton

- src/mainboard/sifive/hifive/fixed-dtfs.dts
- src/mainboard/sifive/hifive/payloadA
- src/mainboard/sifive/hifive/payloadB
- src/mainboard/sifive/hifive/payloadC
- src/mainboard/sifive/hifive/src/main.rs
> Use a smaller dtfs which fits in 16MiB flash map

- src/cpu/lowrisc/ibex/Cargo.toml
- src/cpu/lowrisc/ibex/src/lib.rs
how and where to we specify the imc? Still not sure.
> Add the lowrisc ibex

- azure-pipelines.yml
- src/mainboard/emulation/qemu-riscv/Makefile.toml
> azure-pipelines.yml: Update to use QEMU v4.2.0-rc3

- src/drivers/uart/src/opentitan.rs
Updating the opentitan UART init to match what is used in the opentitan
boot rom:
https://github.com/lowRISC/opentitan/blob/master/sw/device/boot_rom/boot_rom.c#L27
https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/uart.c#L9
Leaving the interrupt disabling commented out for now because that
register doesn't exist in the hjson.
Signed-off-by: pallaud <plaud@google.com>
> Adding opentitan UART init

- src/mainboard/opentitan/crb/Makefile.toml
- src/mainboard/opentitan/crb/link.ld
- src/soc/opentitan/earlgrey/src/bootblock.S
- tools/srec/srec.go
Verilator now runs with these changes, but goes down in flames
at the first sw.
> Changes to get verilator running

- Documentation/opentitan/README.md
> Add docs for OpenTitan

- src/drivers/uart/src/opentitan.rs
verilator shows the hjson is wrong.
> tweak uart register

- src/mainboard/opentitan/crb/src/main.rs
My rust-foo is so bad I figure you can look at this and help.
We want to create a memory device (let m =)
then write one-word slices to it at offset
m.pwrite
I'm just putting this POS up there and figure as I revive my
poor rust memory some of you will just tell me what to do.
> WIP: set up pinmux

- src/mainboard/opentitan/crb/README.md
> Add a README for the opentitan/crb target

- src/drivers/uart/src/lib.rs
- src/drivers/uart/src/opentitan.rs
rminnich@xcpu:~$ cat /dev/pts/3
Welcome to orWelcom
resets at some point but ... one fail at a time.
> fix uart. We get further

- src/arch/arm/armv7/src/lib.rs
- src/drivers/model/src/lib.rs
- src/drivers/sifive/spi/src/lib.rs
- src/drivers/uart/src/lib.rs
- src/drivers/uart/src/log.rs
- src/drivers/uart/src/ns16550.rs
- src/drivers/uart/src/opentitan.rs
- src/drivers/uart/src/pl011.rs
- src/drivers/uart/src/sifive.rs
- src/drivers/wrappers/src/lib.rs
- src/mainboard/sifive/hifive/fixed-dtfs.dts
- src/mainboard/sifive/hifive/src/main.rs
- src/soc/sifive/fu540/src/clock.rs
- src/soc/sifive/fu540/src/ddr.rs
Attempt at closing #75 - any feedback welcome.
Might be totally off base but I believe this is what was being asked for, more formatting changes than I expected after running `cargo make`.
> Add Result<()> return to Driver.init

- src/arch/x86/x86_64/src/bootblock.S
- src/arch/x86/x86_64/src/lib.rs
- src/mainboard/emulation/qemu-q35/Makefile.toml
- src/mainboard/emulation/qemu-q35/fixed-dtfs.dts
- src/mainboard/emulation/qemu-q35/link.ld
> Now running in 64-bit and calling mode; todo: i8250 driver

- README.md
This should reflect what I needed to do on a fresh Debian installation today.
> Update setup steps in README

- src/drivers/uart/src/sifive.rs
- Implement pread
- Add retry timeout requested by TODO
> Improve SiFive UART pread/pwrite

- Makefile
- README.md
right now things are split between the Makefile and README.md and
that is confusing.
> Makefile: add routine tasks

- Documentation/oreboot.md
- Documentation/sifive/setup.md
- README.md
- azure-pipelines.yml
> Cleanup docs

- README.md
The CI badge displays the last pass/fail status for the master branch.
> Add CI badge to main README file

- src/drivers/uart/src/pl011.rs
- src/mainboard/emulation/qemu-armv7/src/main.rs
This fixes the easy things noted in #250. This board will continue to be broken until someone has time to take a closer look at the Payload changes that broke it.
> Mostly fix qemu-armv7

- azure-pipelines.yml
> Add x86 build to CI

- azure-pipelines.yml
- src/mainboard/opentitan/crb/fixed-dtfs.dts
- src/mainboard/opentitan/crb/payloadA
- src/mainboard/opentitan/crb/payloadB
- src/mainboard/opentitan/crb/payloadC
- src/mainboard/sifive/hifive/fixed-dtfs.dts
- src/mainboard/sifive/hifive/payloadA
- src/mainboard/sifive/hifive/payloadB
- src/mainboard/sifive/hifive/payloadC
- tools/layoutflash/src/main.rs
Instead, the user specifies the location of payloads via environment
variables.
> layoutflash: Remove usage of symlinks

- Makefile
Signed-off-by: Ronald G. Minnich <rminnich@google.com>
> move qemu-armv7 away from broken status

- src/mainboard/sifive/hifive/src/main.rs
The device tree property is allowed to be empty, in which case pread
returns EOF. We need to convert that to len=0 instead of returning error
from the whole method.
> Fix EOF problem with device tree in qemu mode.

- src/mainboard/emulation/qemu-q35/fixed-dtfs.dts
- tools/layoutflash/src/main.rs
It resolves two improvements mentioned in #167.
> Add more error checking to layoutflash tool.

- src/lib/device_tree/src/lib.rs
> Add comments to device tree crate.

- src/lib/device_tree/Cargo.lock
- src/lib/device_tree/tests/integration_test.rs
> Add unit tests to device tree crate.

- Makefile.inc
not everyone has a Dediprog - though I'd be happy about a little X-mas present ;)
> Makefile: allow overriding programmer to use for flashing

- src/mainboard/amd/romecrb/Cargo.toml
- src/mainboard/amd/romecrb/src/main.rs
The port 80 uart is very useful when the serial is dead for some reason.
> Add the port 80 uart to the rome

- src/drivers/uart/Cargo.toml
- src/drivers/uart/src/amdmmio.rs
- src/drivers/uart/src/lib.rs
- src/mainboard/amd/romecrb/Cargo.toml
- src/mainboard/amd/romecrb/src/main.rs
Signed-off-by: Ronald G Minnich <rminnich@gmail.com>
> add P0 uart

- .github/auto-merge.yml
> Change 'merge' tag to 'automerge'

- src/arch/x86/x86_64/src/acpi.rs
- src/mainboard/amd/romecrb/src/acpi.rs
Signed-off-by: Titus Rwantare <titusr@google.com>
> Fixed a broken table entry

- src/mainboard/opentitan/crb/link.ld
> mainboard/opentitan: Fix a typo in the linker comment

- src/mainboard/amd/romecrb/Makefile.inc
- src/mainboard/ast/ast25x0/Makefile
- src/mainboard/emulation/qemu-aarch64/Makefile
- src/mainboard/emulation/qemu-armv7/Makefile
- src/mainboard/emulation/qemu-q35/Makefile
- src/mainboard/emulation/qemu-riscv/Makefile
- src/mainboard/sifive/hifive/Makefile
* QEMU => Overrides the QEMU binary
* QEMU_FLAGS => Prepend flags passed to QEMU
> Allow override QEMU variables

- README.md
> Add docs for downloading fsp blobs

- src/vendorcode/fsp/coffeelake/Cargo.lock
- src/vendorcode/fsp/coffeelake/Cargo.toml
Changes have been merged upstream.
> Switch to upstream efi repository

- src/arch/x86/x86_64/src/lib.rs
- src/mainboard/emulation/qemu-fsp/src/main.rs
> qemu-fsp: Enable SSE instructions

- Makefile
- src/mainboard/aaeon/upsquared/.cargo/config
- src/mainboard/aaeon/upsquared/Cargo.toml
- src/mainboard/aaeon/upsquared/Makefile
- src/mainboard/aaeon/upsquared/build.rs
- src/mainboard/aaeon/upsquared/fixed-dtfs.dts
- src/mainboard/aaeon/upsquared/link.ld
- src/mainboard/aaeon/upsquared/src/main.rs
- src/mainboard/aaeon/upsquared/src/romstage.rs
Copied from q35 with minor edits.
Prints "Welcome to oreboot" in QEMU with "make run".
This is still far from working on hardware.
> upsquared: Initial commit

- src/mainboard/amd/romecrb/Cargo.lock
- src/mainboard/amd/romecrb/Cargo.toml
- src/mainboard/amd/romecrb/src/main.rs
- src/mainboard/amd/romecrb/src/mainboard.rs
- src/soc/amd/rome/Cargo.toml
- src/soc/amd/rome/src/lib.rs
> hack the smn -- check values, set if don't match

- src/mainboard/amd/romecrb/Cargo.lock
- src/mainboard/asrock/a300m-stx/Cargo.lock
- src/soc/amd/common/df/Cargo.toml
- src/soc/amd/common/df/src/lib.rs
- src/soc/amd/rome/Cargo.lock
- src/soc/amd/rome/Cargo.toml
- src/soc/amd/rome/src/lib.rs
DF is useful for Picasso, too--so move it to common blocks.
> AMD: Move df to src/amd/common/df.

- src/mainboard/asrock/a300m-stx/src/acpi.rs
- src/mainboard/asrock/a300m-stx/src/main.rs
This is as far as it gets, and it allows for booting into a u-root shell
with the kernel from
https://github.com/oreboot/binaries/tree/master/rminnich/romecrb
> asrock/a300m-stx: ACPI bootstrapping

- src/mainboard/amd/romecrb/Cargo.lock
- src/soc/amd/common/df/Cargo.toml
- src/soc/amd/common/df/src/lib.rs
- src/soc/amd/rome/Cargo.lock
- src/soc/amd/rome/src/lib.rs
Add Fabric Topology reflection.
> Rome: Add Fabric Topology.

- Makefile
> restore mainboard build tests

- src/soc/amd/common/mp/src/mpmailbox.rs
> mpmailbox: Clean up source code.

- src/soc/amd/rome/src/lib.rs
> soc/rome:Have the rome SOC struct contain topology and HSMP

- src/soc/amd/rome/src/hsmp.rs
- src/soc/amd/rome/src/lib.rs
> Tidy up the SMU startup

- src/mainboard/amd/romecrb/src/mainboard.rs
> amd/romecrb: add docs for 3f8 redirect settings

- src/mainboard/amd/romecrb/start.S
Latest version--in wip branch on oreboot now.
AP gets 2k, bsp gets 32k.
> Set up stacks for AP and BSP differently

- src/mainboard/amd/romecrb/start.S
> Rome: Update start.S comments.

- azure-pipelines.yml
> Point azure at main, not master

- README.md
> README: point build status badge to branch `main`

- src/mainboard/amd/romecrb/src/fabric.rs
fabric.rs has some unused directives. Remove those.
> Remove unused top-level directives.

- src/mainboard/asrock/a300m-stx/start.S
the patch broke the prompt. Sorry :/
> Revert my stupid breakage

- src/mainboard/asrock/a300m-stx/Cargo.lock
- src/mainboard/asrock/a300m-stx/Cargo.toml
- src/mainboard/asrock/a300m-stx/src/main.rs
> asrock/a300m-stx: explicitly enable 3f8 decode

- src/mainboard/emulation/qemu-fsp/src/main.rs
Add FSP-S support in QEMU.
Signed-off-by: Tan Lean Sheng <tanleansheng@outlook.com>
> Run FSP-S in qemu

- Documentation/fsp/qemu.md
> Add documentation for current state of QEMU FSP

- src/arch/x86/x86_64/src/asm_defs.h
- src/arch/x86/x86_64/src/bootblock.S
- src/arch/x86/x86_64/src/bootblock_nomem.S
- src/mainboard/aaeon/upsquared/Cargo.lock
- src/mainboard/aaeon/upsquared/Cargo.toml
- src/mainboard/aaeon/upsquared/src/main.rs
- src/mainboard/emulation/qemu-fsp/Cargo.lock
- src/mainboard/emulation/qemu-fsp/Cargo.toml
- src/mainboard/emulation/qemu-fsp/src/main.rs
- src/mainboard/emulation/qemu-q35/Cargo.toml
- src/mainboard/emulation/qemu-q35/src/main.rs
- tools/rpp/src/lib.rs
- tools/rpp_procedural/Cargo.lock
- tools/rpp_procedural/Cargo.toml
- tools/rpp_procedural/src/lib.rs
Add the preprocess_asm! procedural macro for running asm files though
the preprocessor at compile-time.
Additionally, run the x86 bootblock asm files through the preprocessor so
they can share macro definitions.
Signed-off-by: Jordan Hand <jhand@google.com>
> Preprocess x86 bootblock asm files

- src/mainboard/google/trembyle/src/main.rs
- src/mainboard/google/trembyle/src/mainboard.rs
> Update Trembyle with a300 recommendations

- README.md
> README: document crate and mainboard development

- .github/workflows/build.yml
- .github/workflows/fsp-qemu.yml
- Makefile
> Set up GitHub Actions

- Makefile.qemu.inc
Signed-off-by: Angelo Quadara <angeloquadara@google.com>
> Make the mainboard when running 'make run' for QEMU

- src/mainboard/aaeon/upsquared/fixed-dtfs.dts
- src/mainboard/aaeon/upxtreme/Cargo.lock
- src/mainboard/aaeon/upxtreme/Cargo.toml
- src/mainboard/aaeon/upxtreme/Makefile
- src/mainboard/aaeon/upxtreme/build.rs
- src/mainboard/aaeon/upxtreme/fixed-dtfs.dts
- src/mainboard/aaeon/upxtreme/link.ld
- src/mainboard/aaeon/upxtreme/src/main.rs
- src/vendorcode/fsp/coffeelake/Cargo.toml
- src/vendorcode/fsp/coffeelake/build.rs
- src/vendorcode/fsp/coffeelake/src/lib.rs
- src/vendorcode/fsp/coffeelake/src/wrapper.h
Signed-off-by: Lean Sheng Tan <tanleansheng@outlook.com>
> upxtreme: Initial commit

- src/mainboard/sunxi/nezha/Cargo.lock
- src/mainboard/sunxi/nezha/Cargo.toml
- src/mainboard/sunxi/nezha/Makefile
- src/mainboard/sunxi/nezha/fixed-dtfs.dts
- src/mainboard/sunxi/nezha/link.ld
- src/mainboard/sunxi/nezha/src/main.rs
- src/mainboard/sunxi/nezha/start.S
- src/soc/sunxi/d1/Makefile
we can now execute payloads :)
> Nezha next

- Makefile.inc
- Makefile.mainboard.inc
> Build the mainboard as the default target

- README.md
I added some docs on what we do with lockfiles. If I'm misunderstanding the rust-lang.org comments, let me know.
Signed-off-by: Titus Rwantare <titusr@google.com>
> RFC: update guidance on Cargo.lock files

- src/mainboard/emulation/qemu-fsp/src/main.rs
- src/mainboard/emulation/qemu-fsp32/src/main.rs
- src/vendorcode/fsp/qemu/src/lib.rs
- src/vendorcode/fsp/qemu32/build.rs
- src/vendorcode/fsp/qemu32/src/lib.rs
- src/vendorcode/fsp/qemu32/src/wrapper.h
Signed-off-by: Angelo Quadara <angeloquadara@google.com>
> Dump HOB for qemu32, clean up warnings in said code from qemu

- Makefile
> Add 2 more targets require by clippy locally

- .gitmodules
- src/lib/uefi/Makefile
- src/lib/uefi/src/lib.rs
- src/lib/uefi/tests/tests.rs
> fix UEFI lib

- Makefile
> Makefile: install tarpaulin using oreboot's Rust nightly version

- src/mainboard/sunxi/nezha/Makefile
Upstream has changed these commands.
> sunxi/nezha: adjust Makefile for xfel command changes

- src/mainboard/sunxi/nezha/Makefile
Thanks @ldashing  for noticing :pray: 
https://github.com/oreboot/oreboot/commit/b0fd1f594b817187af8b0e574b8ce1c641104d82#r70094126
> sunxi/nezha: fix up raminit for make boot targe

- src/mainboard/amd/romecrb/src/msr.rs
Signed-off-by: Danny Milosavljevic <dannym@scratchpost.org>
Not included:
```
diff --git a/src/mainboard/amd/romecrb/start.S b/src/mainboard/amd/romecrb/start.S
index a19f1b99bd..372e5406e6 100644
--- a/src/mainboard/amd/romecrb/start.S
+++ b/src/mainboard/amd/romecrb/start.S
@@ -113,8 +113,8 @@ outb        %al, $0x80
//lgdtl %cs:(%bx)
.byte 0x66, 0x2E, 0x0F, 0x01, 0x17
movl    %cr0, %eax
-       andl    $0x7FFAFFD1, %eax /* PG,AM,WP,NE,TS,EM,MP = 0 */
-       orl     $0x60000001, %eax /* CD, NW, PE = 1 */
+       andl    $0xDFFAFFD1, %eax /* PG,AM,WP,NE,TS,EM,MP,CD,NW = 0 */
+       orl     $0x00000001, %eax /* PE = 1 */
movl    %eax, %cr0
/* Restore BIST to %eax */
```
Because it was not tested.
> romecrb: Document cache-relevant MSRs better.

- graveyard.md
> graveyard.md: update with updated mainboards

- .github/auto-merge.yml
* Add the yaml start of document marker
* Fix indent all job steps
> Lint github auto-merge manifest

- dprint.json
- src/soc/src/sunxi/d1/clint.rs
- src/soc/src/sunxi/d1/mod.rs
- tools/dtfs_shrinker/src/main.rs
* Install https://dprint.dev/plugins/rustfmt/
* Include rs files in dprint config
> dprint: install rustfmt plugin

- src/mainboard/emulation/qemu-riscv/QEMU.md
Signed-off-by: Ronald G. Minnich <rminnich@google.com>
> emulation/qemu-riscv64 Add temporary qemu info

- xtask/src/gdb_detect.rs
- xtask/src/main.rs
- xtask/src/sunxi/nezha.rs
- xtask/src/target.rs
> xtask: Run cargo clippy --fix

- src/mainboard/sunxi/nezha/compression/src/lib.rs
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#write_with_newline
> compression: Run cargo clippy --fix

- src/mainboard/sunxi/nezha/main/src/main.rs
> [oreboot-nezha-main] Prune unused import: "slice"

- src/mainboard/sunxi/nezha/main/Cargo.toml
- src/mainboard/sunxi/nezha/main/src/main.rs
- src/mainboard/sunxi/nezha/main/src/peripheral.rs
- src/soc/Cargo.toml
This fixes build issues due to some riscv crate versions having been yanked: https://github.com/duskmoon314/aw-pac/issues/28
See other current PRs currently failing.
> bump d1-pac and rustsbi

- src/lib/log/Cargo.toml
- src/lib/log/src/lib.rs
- src/soc/Cargo.toml
This has been working out within #659 - see its use there for reference.
> lib: add log crate

- Makefile
> Use Rust 1.67

- rust-toolchain.toml
- src/mainboard/emulation/qemu-riscv/src/main.rs
- src/mainboard/sunxi/nezha/bt0/src/main.rs
- src/mainboard/sunxi/nezha/main/src/main.rs
> Update toolchain to nightly-2023-02-02

- src/mainboard/sunxi/nezha/bt0/Cargo.toml
from https://github.com/oreboot/oreboot/pull/675#pullrequestreview-1282189392
> Remove dead ufmt dep

- README.md
- graveyard.md
This is a first step in order to catch up with recent development; people got confused, see #681
> Overhaul README and graveyard.md

- src/mainboard/sunxi/nezha/bt0/src/main.rs
Regarding to the issue #683 unneeded code was removed to simplify the jump to mainstage
> Remove unneeded jump code

- .github/workflows/build.yml
- dprint.json
- rust-toolchain.toml
- src/arch/src/lib.rs
- src/arch/src/riscv64/sbi/execute.rs
- src/arch/src/riscv64/sbi/runtime.rs
- src/lib/log/src/lib.rs
- src/mainboard/starfive/visionfive2/Makefile
- src/mainboard/starfive/visionfive2/board.dts
- src/mainboard/starfive/visionfive2/bt0/src/main.rs
- src/mainboard/sunxi/nezha/main/src/main.rs
- xtask/Cargo.toml
- xtask/src/main.rs
- xtask/src/starfive/mod.rs
- xtask/src/starfive/visionfive1.rs
- xtask/src/starfive/visionfive2.rs
- xtask/src/starfive/visionfive2_hdr.rs
- xtask/src/sunxi/nezha.rs
- xtask/src/target.rs
- xtask/src/util.rs
This is a major rework that vastly reduces the boilerplate for our build tasks.
> xtask shared utils

- src/arch/src/riscv64/sbi/runtime.rs
> arch/riscv: comment on register saving/restoring

- src/arch/src/riscv64/sbi/execute.rs
- src/mainboard/sunxi/nezha/main/src/sbi_platform.rs
- arch/riscv: disable timer interrupt when triggered
- sunxi/nezha/main: fix setting the SBI timer
> fix SBI timer

- src/arch/src/riscv64/sbi/execute.rs
> arch/riscv: rework SBI debug prints

- src/arch/src/riscv64/mod.rs
- src/arch/src/riscv64/sbi/csr.rs
- src/arch/src/riscv64/sbi/info.rs
> arch/riscv: rework SBI info prints

- src/mainboard/sunxi/nezha/bt0/src/main.rs
> sunxi/nezha/bt0: simplify eGON header

- Cargo.lock
- src/lib/log/src/lib.rs
- src/soc/src/sunxi/d1/uart.rs
> lib/log: calm down Rust

- Cargo.lock
- Cargo.toml
- src/arch/Cargo.toml
- src/arch/build.rs
- src/arch/src/lib.rs
- src/arch/src/riscv64/sbi/csr.rs
- src/arch/src/riscv64/sbi/execute.rs
- src/arch/src/riscv64/sbi/feature/transfer_trap.rs
- src/arch/src/riscv64/sbi/runtime.rs
- src/mainboard/sunxi/nezha/bt0/Cargo.toml
- src/mainboard/sunxi/nezha/main/Cargo.toml
- src/mainboard/sunxi/nezha/main/src/main.rs
- src/mainboard/sunxi/nezha/main/src/sbi_platform.rs
> redo SBI based on RustSBI 0.4.0 and riscv 0.12.1

- Cargo.lock
- src/lib/compression/Cargo.toml
- src/lib/compression/src/lib.rs
- src/mainboard/sunxi/nezha/main/src/main.rs
- xtask/Cargo.toml
- xtask/src/sunxi/nezha.rs
This required adjusting the sunxi/nezha main stage due to the API change, but also because we need a bigger stack now.
While at it, rework the constants and prints a bit.
With the experience gained now, more rework will follow.
This resolves #772 for a start. We have yet to come to a clear design for building and flashing.
> switch to miniz_oxide for compression

- README.md
- src/mainboard/emulation/README.md
- xtask/README.md
remove the old cruft, add guidance on adding targets
> README rework

- Cargo.lock
- rust-toolchain.toml
- src/arch/src/lib.rs
- src/arch/src/riscv64/sbi/runtime.rs
- src/arch/src/riscv64/util.rs
- src/lib/layoutflash/src/areas.rs
- src/mainboard/canaan/canmv-k230/bt0/src/main.rs
- src/mainboard/canaan/canmv-k230/main/src/main.rs
- src/mainboard/emulation/qemu-riscv/main/src/main.rs
- src/mainboard/rockchip/rk3566/bt0/src/main.rs
- src/mainboard/starfive/visionfive1/bt0/src/main.rs
- src/mainboard/starfive/visionfive1/main/src/main.rs
- src/mainboard/starfive/visionfive2/bt0/src/main.rs
- src/mainboard/starfive/visionfive2/main/src/main.rs
- src/mainboard/sunxi/nezha/bt0/src/main.rs
- src/mainboard/sunxi/nezha/main/src/main.rs
I had already done an earlier upgrade when naked functions were stabilized, so there is another commit.
> Upgrade Rust to nightly-2025-09-06

- .github/workflows/build.yml
- Makefile
split out of #805 again, for a start
> run tests in CI

- xtask/src/qemu/riscv.rs
- xtask/src/starfive/visionfive1.rs
- xtask/src/starfive/visionfive2.rs
- xtask/src/sunxi/nezha.rs
- xtask/src/util.rs
> xtask: define and use common helper for platform directory

- src/lib/layoutflash/src/areas.rs
- src/lib/layoutflash/src/layout.rs
These helpers will then also be used in the bt0/main stages.
> lib/layoutflash rework: simplify create_areas() based on new helpers

- xtask/src/starfive/visionfive1.rs
And move objcopy() into the stage build functions.
> xtask/starfive/visionfive1: factor out build_image()

- xtask/src/starfive/visionfive1.rs
> VF1 xtask rework

- xtask/src/starfive/visionfive2.rs
> VF2 xtask rework
