README.md
src/mainboard/emulation/qemu-armv7/Makefile.toml

Adds cargo-make support to the project to streamline building oreboot.

Add cargo-make

---

payloads/payload/payload.rs

Now we can print these structs with a simple format!(...)
The days of struggling to print structs are over!

Enable printing with {}

---

drivers/src/wrappers.rs
src/lib/device_tree/device_tree.rs
src/mainboard/emulation/qemu-armv7/src/main.rs
src/mainboard/emulation/qemu-armv7/src/print.rs

warning: trait objects without an explicit `dyn` are deprecated

Fix warnings related to missing "dyn"

---

.gitignore
src/drivers/uart/Cargo.toml
src/drivers/uart/src/lib.rs
src/drivers/uart/src/log.rs
src/drivers/uart/src/sifive.rs
src/mainboard/sifive/hifive/Cargo.lock
src/mainboard/sifive/hifive/Cargo.toml
src/mainboard/sifive/hifive/Makefile.toml
src/mainboard/sifive/hifive/src/main.rs
src/mainboard/sifive/hifive/src/print.rs

Just messing around. But this may be handy for debugging later
if we have jtage and can examine memory in qemu or jtag.
This brings up a questions why is print.rs appearing for each mainboard
we get very far if we don't use the sifive init()

add a 'log uart'

---

src/mainboard/ast/ast25x0/Makefile.toml

You can now say
RUST_TARGET_PATH=$(pwd) cargo make -p  release flash
and it will build the target and run flashrom

Add a flash target

---

README.md
src/mainboard/sifive/hifive/Makefile.toml

This makes more sense than using the GCC objcopy since Rust is already
using llvm.

Use llvm objcopy provided by cargo

---

src/arch/riscv/rv64/src/lib.rs

Instead of looping over no assembly let's loop over a WFI instruction
instead.

riscv: Run WFI command when halting

---

payloads/src/external/zimage/mod.rs
payloads/src/lib.rs
src/arch/arm/armv7/src/lib.rs
src/arch/riscv/rv64/src/lib.rs
src/console/src/lib.rs
src/cpu/armltd/cortex-a9/src/lib.rs
src/drivers/clock/src/lib.rs
src/drivers/model/src/lib.rs
src/drivers/sifive/spi/src/lib.rs
src/drivers/uart/src/lib.rs
src/drivers/uart/src/ns16550.rs
src/drivers/uart/src/pl011.rs
src/drivers/uart/src/sifive.rs
src/drivers/wrappers/src/lib.rs
src/lib/device_tree/src/lib.rs
src/mainboard/ast/ast25x0/src/main.rs
src/mainboard/ast/ast25x0/src/romstage/asmram.rs
src/mainboard/ast/ast25x0/src/romstage/asmram/ramtable.rs
src/mainboard/ast/ast25x0/src/romstage/new.rs
src/mainboard/ast/ast25x0/src/romstage/ramconst.rs
src/mainboard/ast/ast25x0/src/romstage/ramtable.rs
src/mainboard/emulation/qemu-armv7/src/main.rs
src/mainboard/sifive/hifive/src/main.rs
src/soc/aspeed/ast2500/src/lib.rs
src/soc/sifive/fu540/src/clock.rs
src/soc/sifive/fu540/src/ddr.rs
src/soc/sifive/fu540/src/ddrregs.rs
src/soc/sifive/fu540/src/lib.rs
src/soc/sifive/fu540/src/ux00.rs
tools/layoutflash/src/main.rs

Currently we get blasted by pages of warnings during compilation, so this fixes all of them and turns warnings into errors to prevent them from happening again. In particular, the compiler will now insist on Rust naming conventions and flag any unused variables/imports/attributes.

Fix warnings

---

src/arch/riscv/rv64/src/lib.rs
src/mainboard/sifive/hifive/src/main.rs

This makes the panic_handler SOC-specific because it needs to know a
thing about UART.
Tested by placing the following in _start:
Result::<(), _>::Err("2 + 2 = 5").unwrap();
The panic looks something like:
PANIC: panicked at 'called `Result::unwrap()` on an `Err` value: "2 + 2 = 5"', /home/ryan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:1084:5
Too bad the line number is not very useful (and probably makes the
binaries non-reproducible).
The size of the bootblob increases from 31K to 36K.

hifive: Print PanicInfo in panic_handler

---

Documentation/sifive/setup.md

Use --prefix=/opt/riscv in documentation

---

azure-pipelines.yml

The messages are a bit more verbose but it is still better than
things like
error 2
which we got before

Fix azure pipelines patch to qemu by checking out known-good ref of qemu

---

azure-pipelines.yml
src/arch/riscv/rv64/src/bootblock.S
src/mainboard/sifive/hifive/Makefile.toml
tools/soc/sifive/fu540/qemu.diff

Upstream QEMU has updated and the old diff no longer applied. While we
are updating the diff let's just update it to include the latest patches
on the QEMU list adding support for everything oreboot needs.
We need to also update the run Makefile to use the new QEMU arguments.
Once the patches are in upstream QEMU we can remove all the
modifications to QEMU in the testing and documentation.

sifive/qemu.diff: Update for mainline QEMU

---

src/lib/device_tree/src/lib.rs

Instead of blindly converting any data with the first byte between 0x20
and 0xff into a string let's safely see if it is valid UTF8 string.
This fixes the strange print being seen when printing the QEMU device
tree clock-frequency. This also removes ome unsafe code!

lib/device_tree: Check if the string is UTF8

---

src/soc/sifive/fu540/src/init.S

For now, rust runtime is broken as it demands 16 bit atomic
load and store ops, which riscv can not do.
Add a gross hack to get us building again until they fix their
code.
This allows me to run again.
Arguably, this belongs in arch, but since it should not exist
at all, and I don't want to add more .S files, it goes here.
We'll revert it very soon.

fu540 init: add a hack for broken rust riscv runtime

---

src/soc/sifive/fu540/src/init.S

Fixed by https://github.com/rust-lang/compiler-builtins/pull/324
This reverts commit f506d39cebf198d0bf2503cac99880ca947e6b6e.

Revert "fu540 init: add a hack for broken rust riscv runtime"

---

src/arch/riscv/rv32/Cargo.toml
src/arch/riscv/rv32/src/lib.rs
src/arch/riscv/rv32/src/mod.rs
src/arch/riscv/rv32/src/reg.rs

There are lots of options, e.g. imc vs. imac, so we should try to keep this code clean
of all the variants. That should likely be amended by the SOC.

Add the rv32

---

src/mainboard/sifive/hifive/Makefile.toml

**What:**
* Fixes #135 by inserting the `sed` suggested by @rjoleary, and it’s inverse, into `Makefile.toml`.
* `s#/release/#/debug/#` instead of `s/release/debug/`, to only do the replacement if word is within a path, in case there’s intentional uses of these words in the DTFS going forward (your use of the Device Tree is…interesting :wink:).
**Why:**
To address the comment about the value of debug on #135: the default debug profile includes `overflow-checks = true`, so the target will panic on integer overflow where the developer hasn’t made it explicit (e.g. [u32::wrapping_add](https://doc.rust-lang.org/std/primitive.u32.html#method.wrapping_add)). Release mode will silently allow wrap-around to happen, like C/C++. This may make a debug target worth keeping around, maybe there are …

In-place sed for debug fixed-dtfs.dts

---

src/mainboard/opentitan/crb/fixed-dtfs.dts
src/mainboard/opentitan/crb/src/main.rs

The real part I thought had 512K, but verilator only takes 64k.
Regardless, clean up the dts and use that now.
The payload loading with the slice fails now, it did not before,
help.

Fix the dts and have the Makefile use it; other little fixes

---

src/drivers/uart/src/opentitan.rs
src/mainboard/opentitan/crb/Makefile.toml
src/mainboard/opentitan/crb/README.md
src/mainboard/opentitan/crb/link.ld
src/mainboard/opentitan/crb/src/main.rs

This fixes the baud rate to control register value calculations in
the opentitan uart driver. This also fixed the linker script to make
an earlgrey compatible binary. This will create a bootblob.bin file
that can be written to the earlgrey flash.
Signed-off-by: Ian Goegebuer <ian@iangoegebuer.com>

Fix oreboot on opentitan (earlgrey)

---

src/arch/x86/x86_64/src/bootblock.S
src/mainboard/emulation/qemu-q35/Makefile.toml
src/mainboard/emulation/qemu-q35/link.ld

This now gets through the lidt and lgdt, and the little call trick
avoids linker messes.
You can do this:
qemu-system-x86_64 -bios target/x86_64-unknown-none/release/bootblob.bin -monitor stdio
QEMU 3.1.50 monitor - type 'help' for more information
(qemu) VNC server running on ::1:5900
x/i $pc
0xffff00a1:  eb fe                    jmp      0xffff00a1
(qemu) quit
Next: 64-bit mode.

Clean up the x86 bootblock

---

src/drivers/uart/src/null.rs
src/mainboard/emulation/qemu-q35/src/main.rs

Also clean up warnings, and drop Null::new() given that unit-like types
introduce a type-named constant of the same type.
Signed-off-by: Garret Kelly <gdk@google.com>

uart/null: Replace Null with unit-like type

---

README.md
src/mainboard/emulation/qemu-riscv/Makefile.toml
src/mainboard/emulation/qemu-riscv/src/main.rs

Unwraps the result of the uart init and specifes the "raw" format when QEMU is resizing and running.

Fix warnings for the qemu-riscv mainboard

---

Documentation/sifive/setup.md
src/drivers/sifive/spi/src/lib.rs
src/mainboard/sifive/hifive/Cargo.lock
src/mainboard/sifive/hifive/Makefile.toml
src/mainboard/sifive/hifive/openocd.cfg
src/mainboard/sifive/hifive/src/main.rs
src/soc/sifive/fu540/Cargo.toml
src/soc/sifive/fu540/src/lib.rs
src/soc/sifive/fu540/src/spi.rs

In response to #152, implements enough of the SPI driver to enable the full 256 MB memory space mapped by the SPI controller on the FU540. I tried to copy the `fu540_spi_setup()` and `fu540_spi_mmap()` APIs created in Coreboot to do this configuration.
This doesn't yet allow us to configure SPI0 to use its full memory space, though, because right now Oreboot executes exclusively out of the SPI0 memory space. Without an SD card boot flow or the ability to jump to a second boot stage not executing out of the boot flash, this is the most I can do right now.
I'm also including a patch to include an OpenOCD config file and a cargo-make target to program the Unleashed with OpenOCD. It's the most convenient programming method available to me, but if we don't want it in the project I can remove …

Implement SiFive SPI Driver

---

Makefile
Makefile.inc
azure-pipelines.yml
src/arch/riscv/rv32/src/lib.rs
src/arch/riscv/rv64/src/lib.rs
src/arch/x86/x86_64/src/lib.rs
src/drivers/uart/src/lib.rs
src/drivers/uart/src/opentitan.rs
src/mainboard/ast/ast25x0/src/main.rs
src/mainboard/emulation/qemu-armv7/src/main.rs
src/mainboard/emulation/qemu-q35/src/main.rs
src/mainboard/emulation/qemu-riscv/src/main.rs
src/mainboard/nuvoton/npcm7xx/src/main.rs
src/mainboard/opentitan/crb/src/main.rs
src/mainboard/sifive/hifive/src/main.rs

The current invocation seems no longer supported in cargo-binutils
0.2.0. The change herein appears to be forwards (tested 0.2.0) and
backwards (tested on 0.1.6) compatible.

Fix build with latest nightly rustc and cargo objcopy

---

Makefile.inc

cargo-binutils v0.2.0 now tries to rebuild your crates which was
problematic when also using cargo-xbuild.

Use rust-objcopy instead of cargo-objcopy

---

Makefile

Signed-off-by: Nickolas Fotopoulos <foton@google.com>

Pin rust toolchain to nightly-2020-04-22, the last known working version

---

Makefile

Pin cargo-xbuild and cargo-binutils versions in `make firsttime`. In doing so, revert cargo-xbuild by three versions (0.5.32 &rarr; 0.5.29), which fixes #259. I verified that all newer versions are broken for us, but have not yet taken the time to figure out whether the five issues reported against cargo-xbuild in the relevant time period correspond to our breakage or not.

Pin cargo package versions

---

payloads/src/external/zimage/mod.rs
src/mainboard/emulation/qemu-armv7/src/main.rs
src/mainboard/emulation/qemu-armv7/src/romstage.rs

This fixes the compilation issues with qemu-armv7 version but there is still a linker error related to the nostd usage. Plan is to fix the linker error in subsequent changes.
Linker error that remains is: 
note: rust-lld: warning: lld uses blx instruction, no object with architecture supporting feature detected
rust-lld: error: undefined hidden symbol: __aeabi_uldivmod
#250 is the associated issue.

Fix compilation issues with qemu-armv7.

---

azure-pipelines.yml
src/soc/sifive/fu540/src/lib.rs
src/soc/sifive/fu540/src/reg.rs

Current codes detect QEMU by inspecting a 32-bit value at address
0x1000 (which is the MSEL pin state). This worked as QEMU has not
implemented MSEL support yet. With MSEL supported [1] added in the
upstream QEMU recently, the detecting logic no longer works, and
we have to update the logic to look at the value at address 0x1008
instead, where QEMU differs from real hardware.
[1] http://patchwork.ozlabs.org/project/qemu-devel/patch/1592268641-7478-3-git-send-email-bmeng.cn@gmail.com/
Signed-off-by: Bin Meng <bin.meng@windriver.com>

soc/sifive/fu540: Update QEMU detect logic

---

Makefile

This new target will automatically run rustfmt on all rust code in this
repository (note: only rust code that is inside some cargo crate will be
formatted).
It also introduces special `check` parameter that we can later use in CI
to verify that all pull requests are properly formatted, by running:
```
$ make --keep-going format check=true
```

Add format target to Makefile.

---

src/lib/device_tree/Cargo.lock
src/lib/device_tree/src/lib.rs

It also changes the logic to first read the whole header into 40 byte
array and then convert them to integers. This has the advantage that we
check the Result from pread just once (instead 10 times), and we can
also check the actual size returned by pread (before the code did not
check that we actually read 4 bytes).

Extract method reading device tree header.

---

Makefile
README.md
azure-pipelines.yml

This also introduces variables to switch tooling versions.

Makefile: separate prepare target for CI from firsttime

---

src/drivers/wrappers/src/lib.rs
src/lib/device_tree/src/lib.rs
src/lib/device_tree/tests/integration_test.rs
src/mainboard/sifive/hifive/src/main.rs

ref #38
Generics allow us to avoid dynamic dispatch and should make the code
faster.

Use generics instead of trait objects in FdtReader

---

Makefile
azure-pipelines.yml

The problem was the ordering of arguments inside filter-out function (in
the comment the arguments were in invalid order which is why it was not
working).
I am adding emulation/qemu-armv7 and nuvoton/npcm7xx to the list of
broken targets because they fail to build.

Use wildcard to define list of mainboards.

---

Makefile
azure-pipelines.yml
payloads/src/external/zimage/mod.rs
payloads/src/payload/payload.rs
src/arch/x86/x86_64/src/ioport.rs
src/drivers/sifive/spi/src/lib.rs
src/lib/device_tree/src/lib.rs
src/lib/print/src/lib.rs
tools/layoutflash/src/main.rs

Clippy is a standard lint tool for rust, for more information see https://github.com/rust-lang/rust-clippy.
Closes #282

Add `make clippy`, fix existing warnings and run in CI.

---

azure-pipelines.yml
scripts/generate-size-report.sh

This new script will print a simple CSV with two columns - the name of
the mainboard (two directory names) and the size of the bootblob in
bytes.
It would be nice to export this data in strucutre manner somewhere and
track over time, but for now at least we will have this information in
the azure pipeline logs.

Generate the report of binary sizes in CI.

---

src/mainboard/sifive/hifive/fixed-dtfs.dts
tools/layoutflash/src/main.rs

Closes #167 - make `offset` property optional inside fixed-dtfs used by
layoutflash. If not set, the end of the previous area will be used as
offset.

Compute the offset based on previous areas.

---

src/drivers/wrappers/src/lib.rs
src/drivers/wrappers/tests/tests.rs
src/lib/device_tree/tests/integration_test.rs

While writing tests, I found that there is a bug in SliceReader (it
always returns the size of the input buffer instead of the number of
bytes actually read).
Closes #156 - existing tests cover various cases, including nested
nodes, different type of properties (empty, number, string) and few
error conditions.
Closes #155 - added test cases for empty properties and shows it works
(though because of Driver API, when property is empty the Driver returns
EOF error, but that is WAI).

Add more tests for device tree reader.

---

Makefile.qemu.inc
src/arch/x86/x86_64/Cargo.lock
src/arch/x86/x86_64/Cargo.toml
src/arch/x86/x86_64/src/bzimage.rs
src/arch/x86/x86_64/src/lib.rs
src/drivers/wrappers/src/lib.rs
src/drivers/wrappers/tests/tests.rs
src/lib/device_tree/tests/integration_test.rs
src/mainboard/amd/romecrb/Makefile
src/mainboard/emulation/qemu-q35/Cargo.lock
src/mainboard/emulation/qemu-q35/Makefile
src/mainboard/emulation/qemu-q35/src/main.rs

Used a bzImage library from rminnich/romecrb branch and used it to load a bzImage of a linux kernel made with tinyconfig.
Emulator needs to provide 2GB RAM for that particular kernel config to boot.

Updated q35 emulation to use a bzImage payload

---

src/lib/device_tree/Cargo.toml
src/lib/device_tree/src/lib.rs
src/lib/device_tree/tests/integration_test.rs
src/mainboard/amd/romecrb/Cargo.lock
src/mainboard/sifive/hifive/Cargo.lock
src/mainboard/sifive/hifive/src/main.rs
tools/layoutflash/Cargo.lock
tools/layoutflash/src/main.rs

Closes #74.
We are dropping the core::Iterator trait from `FdtIterator` as we never
actually benefited from implementing it. Implementing next with custom
lifetimes allows us to make it more performant (`Entry` can reference
internal buffers in `FdtIterator`).
I am also adding error handling to the `FdtIterator` following
`std::io::Lines` approach. I also removed the use of unsafe from device
tree crate (we check if string is indeed utf8 and return error if it is
not).
I also slightly changed the API of Entry to include both StartNode and
EndNode. This is following similar pattern to StAX XML parsers and
allows users of the iterator to write more composable code.

Refactor FdtIterator to use streaming iterator API.

---

azure-pipelines.yml

1. Do a shallow git clone to save 10 seconds. This will represent more savings as the repo gets bigger.
2. Add proper dependencies between steps to gain some parallelism.

CI parallelization

---

src/drivers/uart/Cargo.toml
src/drivers/uart/src/i8250.rs
src/drivers/uart/src/lib.rs
src/mainboard/amd/romecrb/Cargo.lock

Unfortunately i8250 is port mapped so I am unable to use register blocks.
I still managed to add some unit test to check that the driver initialises the UART.

Add unit test to i8250 driver and remove unused code

---

src/drivers/uart/Cargo.toml
src/mainboard/emulation/qemu-q35/Cargo.lock

Running `make clippy` shows that src/drivers/uart does not specify the
exact version to use and that it will become an error in future
versions. To avoid a future breakage, just lock the version now.

Lock version of heapless dependency.

---

Makefile

There are some mainboards (ref #283) that fail to compile because version of compiler_builtins is not locked. The simplest fix is to just update the toolchain to a newer one.

Update rust toolchain version

---

src/drivers/model/src/lib.rs
src/drivers/model/src/tests.rs
src/lib/device_tree/src/lib.rs
src/lib/device_tree/tests/integration_test.rs

This is similar to std::io::Read::read_exact, that reads the exact
number of bytes to fill in the input buffers. The current code often
assumes that the buffer will be fully filled in (especially when reading
u32 into a 4 byte buffer), this method will make it much easier to write
it correctly.

Add Driver::pread_exact method.

---

payloads/Cargo.lock
payloads/Cargo.toml
payloads/src/payload.rs
src/arch/x86/x86_64/Cargo.lock
src/arch/x86/x86_64/Cargo.toml
src/arch/x86/x86_64/src/bzimage.rs
src/lib/device_tree/Cargo.lock
src/lib/device_tree/Cargo.toml
src/lib/device_tree/src/lib.rs
src/lib/print/src/lib.rs
src/mainboard/amd/romecrb/Cargo.lock
src/mainboard/emulation/qemu-q35/Cargo.lock
src/mainboard/emulation/qemu-riscv/Cargo.lock
src/mainboard/opentitan/crb/Cargo.lock
src/mainboard/sifive/hifive/Cargo.lock
src/mainboard/sifive/hifive/src/main.rs
tools/layoutflash/Cargo.lock

This change uses generics inside print::WriteTo type as well as in all
places that used this type.
Ref: #38

Use generics for print crate.

---

Makefile
src/drivers/uart/src/log.rs
src/drivers/uart/src/sifive.rs
src/mainboard/sifive/hifive/src/main.rs
src/soc/sifive/fu540/src/clock.rs
src/soc/sifive/fu540/src/ddr.rs
src/soc/sifive/fu540/src/ux00.rs

This change creates a separate list for BROKEN crates that do not work
with clippy yet (previuosly we shared the list for `cargo test`). It
also removes sifive/hifive mainboard from broken list and fixes all
existing errors.

Run clippy on sifive/hifive mainboard.

---

Makefile
src/lib/device_tree/src/lib.rs
src/mainboard/emulation/qemu-armv7/Cargo.lock
src/mainboard/emulation/qemu-armv7/fixed-dtfs.dts
src/mainboard/emulation/qemu-armv7/src/main.rs

This change fixes the rust code (broken by recent refactorings) and
fixes the fixed-dtfs layout to provide enough space for the actual
bootblob (it is over 6M but only 512K was reserved).
Ref #283

Fix emulation/qemu-armv7 mainboard.

---

src/mainboard/emulation/qemu-q35/src/main.rs

It was set for a size of 0x100_000, which is only 1M.

qemu-q35: fix the bzimage struct so it as 16M, not 1M

---

src/mainboard/asrock/a300m-stx/patch.go

asrock/a300m-stx: fix arg parsing in patch.go

---

src/mainboard/opentitan/crb/link.ld

With this patch oreboot now boots after the OpenTitan boot ROM in QEMU.

mainboard/opentitan: Get oreboot booting in QEMU

---

src/mainboard/emulation/qemu-armv7/Makefile

qemu-arvm7 is currently missing 'make run', add it.

Enable 'make run' for qemu-armv7 mainboard

---

Makefile
src/vendorcode/fsp/coffeelake/Cargo.lock
src/vendorcode/fsp/coffeelake/Cargo.toml

Remove fsp-coffeelake from broken crate list
This contains two fixes:
1. nightly-2020-10-30 broke the efi crate. This changes includes the
following fix:
https://github.com/gurry/efi/commit/b639a367ddc794f0ab90e1d3278956b6bd23dd5e
2. The efi crate defines a global allocator which breaks everything.
This change includes the following fix which is pending a merge
upstream:
https://github.com/rjoleary/efi/commit/5c169fc6fd9c402c5f7083c8461874bc8c4d755e

Remove fsp-coffeelake from broken crate list

---

Documentation/getting-started.md
Makefile
Makefile.inc

Most of the functionality of `cargo xbuild` has been integrated into `cargo build` anyway. Even `cargo xbuild` website strongly recommends using `cargo build`.
* Makefile.inc (ELF): Use 'cargo build -Z build-std=core,alloc' instead
of 'cargo xbuild'.
* Makefile: Don't install 'cargo xbuild'.
* Documentation/getting-started.md: Update.
Signed-off-by: Danny Milosavljevic <dannym@scratchpost.org>

Replace 'cargo xbuild' by 'cargo build -Z build-std=core,alloc'

---

Makefile.inc

* Makefile.inc (OBJCOPY): New variable.
(bootblob.bin): Use it.
My goal is to make oreboot (optionally) buildable by the official Rust Docker image from Dockerhub, reducing the entire build instructions to just this (without having to install Rust locally before):
```
export PAYLOAD_A=`pwd`/bzImage
TARGET_DIR=`pwd`/src/mainboard/amd/romecrb/target/x86_64-unknown-none/release
mkdir -p "${TARGET_DIR}"
FIXED_DTFS=fixed-dtfs.dtb
dtc src/mainboard/amd/romecrb/fixed-dtfs.dts -O dtb -o "${TARGET_DIR}/${FIXED_DTFS}"
docker pull rustlang/rust:nightly
docker run --rm -e PAYLOAD_A="${PAYLOAD_A}"  -e USER="${USER}" --user "$(id -u)":"$(id -g)" -v "${PWD}:${PWD}" -w "${PWD}" rust-nightly:latest make -C src/mainboard/amd/romecrb OBJCOPY=objcopy
(and then somehow patch the resulting binaries into your …
```

Make OBJCOPY configurable.

---

Makefile.inc

Such of the following:
fixed-dtfs.dts:13.20-19.15: Warning (unit_address_vs_reg): /flash-info/areas/area@0: node has a unit name, but no reg property
The fixed-dtfs nodes do not have reg properties.

Squelch dtc warnings

---

src/drivers/uart/src/amdmmio.rs
src/mainboard/amd/romecrb/src/main.rs

This fixes the AMD MMIO UART drivers, and adds com2.
First, the THRE check is fixed (the check was inverted).
Then the baud rate is set to 115200.
Then, console output is written to COM2 as well.

AMD MMIO UART fixes

---

Makefile

azure can no longer find gcc-5

upgrade gcc-5 to gcc-6

---

src/drivers/uart/src/i8250.rs

Previously, the baud rate would NOT be correctly set up when using I8250. That's why it always only worked with a combination of MMIO and I8250 drivers on the same port.
This fixes the AMD 8250 (legacy) baud rate setup--it now works just fine standalone.

Change i8250 DLAB constant--fixed i8250 serial port baud rate setup

---

src/drivers/uart/src/amdmmio.rs
src/mainboard/amd/romecrb/src/mainboard.rs

This patch completes the UART setup for AMD romecrb.
It sets up UART0 and UART1. It does the pinctrl setup, powers the UART blocks on, powers AMBA on and sets the UART clocks to 1.8 MHz.

romecrb: Setup UART0 and UART1 pinctrl, power them on and set the clocks to 1.8 MHz

---

src/custom_targets/x86_64-unknown-none.json

LLVM updated all x86 targets to allow mixed pointer sizes
(https://reviews.llvm.org/D64931). Our misalignment was causing a
warning.
Fixes oreboot#346.
Signed-off-by: Nickolas Fotopoulos <foton@google.com>

Update x86_64-unknown-none data-layout to upstream

---

Makefile
rust-toolchain

The `rust-toolchain` file appears to be the official way to check toolchain overrides into version control. https://rust-lang.github.io/rustup/overrides.html?highlight=toml#the-toolchain-file
It appeals to me because it separates data from code.
Fixes #275.
Signed-off-by: Nickolas Fotopoulos <foton@google.com>

Factor out toolchain overrides into rust-toolchain file

---

src/mainboard/amd/romecrb/Cargo.toml
src/mainboard/amd/romecrb/src/mainboard.rs

Signed-off-by: Danny Milosavljevic <danny.milo@datacom.wien>

romecrb: Use vcell for registers (instead of integers).

---

src/mainboard/asrock/a300m-stx/src/main.rs
src/mainboard/asrock/a300m-stx/src/mainboard.rs

asrock/a300m-stx: run init() without UART1

---

src/mainboard/amd/romecrb/src/main.rs

No change: linux hangs on boot.

mainboard/amd/rome: moar settings from the standard bios.

---

src/soc/amd/rome/src/df.rs
src/soc/amd/rome/src/lib.rs

From coreboot.  Necessary to set up PCI config access routing.

Rome: Add DF indirect access helpers.

---

src/soc/amd/rome/src/hsmp.rs
src/soc/amd/rome/src/lib.rs

After reading some more Rust docs, I think those functions are technically not unsafe in the sense of Rust.
So this marks them safe.

hsmp: Mark functions safe.

---

src/soc/amd/picasso/src/lib.rs

Since the module isn't using llvm asm, remove llvm asm directive.

Picasso: Remove unnecessary llvm asm directive.

---

src/mainboard/amd/romecrb/src/main.rs
src/soc/amd/rome/src/lib.rs

This is prior to adding all the little MPx parts to the system.
They are properly part of the soc.
As a first pass, set up a soc struct and set up its new and init
methods.
Longer term, the cpu_init ought to be called from the soc, but one thing
at a time.

make soc a part

---

src/arch/x86/x86_64/Cargo.lock
src/drivers/uart/Cargo.lock
src/soc/amd/rome/Cargo.lock
src/soc/amd/rome/src/lib.rs

builds and boots. Runs test42 and smu_version for the first 4 MPs.

soc/amd/rome: Add the other MPs to the SOC

---

src/mainboard/amd/romecrb/src/bootblock.S
src/mainboard/amd/romecrb/src/main.rs
src/mainboard/amd/romecrb/start.S

This makes `start.S` set up different stacks for different cores and threads.
It has been successfully tested.
The actual mechanism to enable physical cores in the first place is being documented by Paul, but he is not done yet (i.e. that part is not in this pull request). Therefore, this cannot be tested right now by people without AGESA access.
Note that it is my intention to have oreboot still only run on the bootstrap core. The other cores are only enabled so (1) Linux can use them and (2) we can set up MSRs for them.
The idea is that `_start` would check the `BSP` flag and then would `hlt` if it's not the bootstrap core--only for it to be later woken up for a short while by an interrupt (NMI, IPI or similar).
Note: TODO (later): adapt call `setup_acpi_tables(w, ?, <number of cores>)`

Rome: Provide different stacks for different cores.

---

src/mainboard/amd/romecrb/src/mainboard.rs

This gives me working BMC console, Danny reports same.

Make 3f8 legacy work, especially with bmc consoles

---

src/mainboard/amd/romecrb/src/acpi.rs
src/mainboard/amd/romecrb/src/main.rs

Autodetect the number of cores and use it to set up the ACPI tables.

Rome: setup_acpi_tables: Autodetect the number of cores.

---

src/drivers/uart/src/debug_port.rs
src/drivers/uart/src/i8250.rs
src/lib/print/src/lib.rs
src/mainboard/aaeon/upsquared/src/main.rs
src/mainboard/amd/romecrb/src/main.rs
src/mainboard/amd/romecrb/src/mainboard.rs
src/mainboard/asrock/a300m-stx/src/main.rs
src/mainboard/emulation/qemu-fsp/src/main.rs
src/mainboard/emulation/qemu-q35/src/main.rs
src/soc/amd/common/boot/src/lib.rs

This patchset factors out more common parts from AMD mainboard "romecrb".
First, make I8250 and DebugPort actually own their respective IOPorts.
Then, add WriteToDyn to print as an extra fmt::Write implementation that is implemented on a `dyn Driver` rather than a on concrete implementation of `Driver`.
Then, make the `romecrb` mainboard return a list of possible text output drivers.
Use that in `main.rs` in order to find out which text output drivers to use.
Last, clean out obsolete comment about custom bootblock.S from src/soc/amd/common/boot/src/lib.rs .

Factor out common parts from AMD mainboard "romecrb"

---

src/drivers/uart/src/amdmmio.rs
src/mainboard/amd/romecrb/src/mainboard.rs
src/mainboard/asrock/a300m-stx/src/main.rs

This patch series cleans up the naming of the AMD UARTs in oreboot (to make it less confusing) and then makes romecrb use both UARTs again.

Clean up UART handling on Rome

---

src/mainboard/amd/romecrb/src/mainboard.rs

After the big refactoring, I forgot to call the Driver::init for all the text output drivers. That made the serial ports not print any output on the BMC serial on real hardware.
This patch adds it again.

Rome: Init all the text output drivers automatically.

---

src/mainboard/amd/romecrb/src/mainboard.rs

For some reason, we are setting a reserved bit in HPETCONFIG. If there's no good reason, we shouldn't.

Rome: Remove setting of reserved bit in HPETCONFIG.

---

src/soc/amd/common/boot/src/bootblock.S

`bootblock.S` had trashed %esp that `start.S` meticiously set up.
This patch rectifies that.
Also, clean up some comments and also make the rounding-up more resilient.

AMD Bootblock: Fix up.

---

src/soc/amd/common/boot/src/lib.rs

Clean up Core::X86::Apic::LocalDestination handling:
* The first print will always print 0, so remove it.
* Document which register it is.
Future work should take care not to touch the reserved bits 23:0 and also move the poke to src/soc or some general AMD interrupt routing crate.

AMD common: Clean up and document Core::X86::Apic::LocalDestination

---

src/mainboard/amd/romecrb/src/main.rs

This setup is already done in src/amd/common/boot, so don't do it again.

AMD Rome: Remove duplicate LDN setup.

---

src/mainboard/amd/romecrb/src/mainboard.rs

Since our serial ports work well now, stop printing to port 0x80 by default on amd romecrb.

AMD Romecrb: Don't use port 0x80 as text output destination anymore.

---

src/soc/amd/common/boot/src/interrupts.rs
src/soc/amd/common/boot/src/lib.rs

I don't know who thought relying on a traditional 1981 PIC in 2021 was a good idea--but here we go, we now enable it and then set it to ignore all external interrupts.

AMD: Add init_pics.

---

src/mainboard/asrock/a300m-stx/src/mainboard.rs

This aligns a bit more with romecrb again.

asrock/a300m-stx: Remove extraneous MSR APIC configuration

---

src/soc/amd/common/boot/src/bootblock.S

Boot times with this time are unchanged, but for reference
0s RESET
12s first print
40s "on to payload..."
1:35 first kernel print
2:25 u-root prompt
The kernel in this case is
Linux version 5.8.0 (rminnich@t510) (gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0, GNU ld (GNU Binutils for Ubuntu) 2.35.1) #16 Fri May 14 17:52:25 UTC 2021
commit bcf876870b95592b52519ed4aafcf9d95999bc9c (grafted, HEAD, tag: v5.8)
github.com/linuxboot/mainboards repo 74f1a1de20644143f48a1243addfda56e27b4395 with cpu.config

soc/amd/common: Turn off CD and NW in CR0

---

src/mainboard/emulation/qemu-riscv/fixed-dtfs.dts
src/mainboard/sifive/hifive/fixed-dtfs.dts

This patch fixes typos in boot phase name as Oreboot
doesn't have stage name Ramstage unlike coreboot.
Ramstage -> Romstage
Signed-off-by: Subrata Banik <subrata.banik@intel.com>

mb/{emulation, sifive}: Fix typos

---

README.md

In an effort to support a larger breadth of platforms, oreboot is now
also targeting x86. In order to encourage x86 contributions, remove
language about oreboot explicitly not supporting x86 in the README.
Signed-off-by: Jordan Hand <jhand@google.com>

Remove language about lack of x86 support

---

tools/rpp/Cargo.lock
tools/rpp/Cargo.toml
tools/rpp/src/lib.rs
tools/rpp/src/testdata/sample.S
tools/rpp/tests/test.rs
tools/rpp_procedural/src/lib.rs
tools/rpp_procedural/tests/test.rs
tools/rpp_procedural/tests/testdata/external_macros.S
tools/rpp_procedural/tests/testdata/simple.S

To support more full-featured preprocessing, add the following features
to the rpp and rpp_procedural crates:
* Fix block comment bug that led to wrong line numbers in parsing errors
* Add support to preprocess_asm! to inject macro definitions
Additionally, add some basic tests for the rpp and rpp_procedural crates.

Add features to the rust preprocessor library

---

azure-pipelines.yml

Update the fspsdk submodule and re-enable the FSP test in CI
When you pull this change you may need to update you submodules:
```
git submodule update --init
```

Re-enable fsp CI tests

---

Makefile.renode.inc
src/mainboard/sifive/hifive/Makefile
src/mainboard/sifive/hifive/renode-debug.resc
src/mainboard/sifive/hifive/renode-release.resc
src/mainboard/sifive/hifive/renode-sifive-fu540.repl

Use `make run_renode` to invoke renode
Enabled for sifive unleashed board

Add renode support to oreboot

---

Makefile.inc

Makefile.inc: add `make fix` target for clippy fix

---

Makefile

This was needed to make local clippy work.
mainboards build without it, but clippy fails. True!

Add rustup targets for local clippy

---

src/mainboard/aaeon/upxtreme/src/main.rs
src/mainboard/emulation/qemu-fsp/src/main.rs
src/mainboard/emulation/qemu-fsp32/src/main.rs
src/vendorcode/fsp/coffeelake/src/lib.rs
src/vendorcode/fsp/qemu/src/lib.rs
src/vendorcode/fsp/qemu32/src/lib.rs

Refactor the boards which use FSP so that the FSP UPD structures are
kept in architecture-specific crates instead of board-specific crates.
This allow boards to share the same parameters for the same CPU
generation.
Signed-off-by: Jordan Hand <jhand@google.com>

FSP: Organize UPD parameters by arch instead of board

---

Makefile
rust-toolchain.toml
src/drivers/model/src/lib.rs
src/soc/amd/common/pci/src/lib.rs

- bump binutils to 0.3.4
- rust-toolchain: switch to nightly-2021-10-21
- Remove feature const_panic (stabilized)
- drivers/model: remove &mut passed to `pread`

Switch to Rust 1.58.0

---

Makefile

rust language server (rls) spits out target/debug directories all over the place when browsing code in an IDE.
This cleans them up.

make clean removes more targets

---

.github/workflows/build.yml
Makefile

So maybe this was just confusing to me but this is how I understand the mainboard(s) target atm:
```
MAINBOARDS := $(wildcard src/mainboard/*/*/Makefile)
.PHONY: mainboards $(MAINBOARDS)
mainboard: $(MAINBOARDS)
$(MAINBOARDS):
cd $(dir $@) && make cibuild
``` 
Even though `mainboards` (mind the s) is declared as a phony target, there is no such target. **EDIT**: _There actually is, but it is empty._
However, there is a list of targets defined through the `$(MAINBOARDS)` variable. These _are_ phony and _exist_.
The `mainboards` variable is expanded to all of the makefiles that are found at the described path (first line), so its value is something like:
`src/mainboard/aaeon/upxtreme/Makefile src/mainboard/emulation/qemu-aarch64/Makefile src/mainboard/emulation/qemu-q35/Makefile ...`
Since …

Remove unneeded mainboards string

---

src/drivers/timer/src/hpet.rs
src/drivers/uart/src/debug_port.rs
src/mainboard/emulation/qemu-q35/src/main.rs

Add a function `enable()` to the HPET driver. This allows the calling driver, `DebugPort` in this case, enable the timer if it wants to use it. This is necessary for the qemu-q35 board as it does not init the timer, like the romecrb board for example.
This fixes #500.
I was contemplating whether `hpet0()` should do this automatically, but as the code is already used in other boards and there is a comment saying the caller should ensure enablement I felt like this is sensible solution. Happy to hear other opinions.

Initialize HPET driver in DebugPort

---

tools/rpp/src/lib.rs
tools/rpp/src/testdata/sample.S
tools/rpp/src/testdata/test.inc
tools/rpp/tests/test.rs

#497 
This PR attempts to adds multi-line macro support in rpp. Macros like the one given below are supported now. 
```
#define MACRO \
(A + \
B) // This expands to (A + B)
```
Changes introduced:
- Add `split_lines_re` Regex to `Context` struct which is used to split a line preserving escaped newlines. 
- Add test `macro_with_newline` which checks multi-line macro expansion. 
- The current behavior is to ignore escaped newlines while macro expansion, so multi-line macros essentially are treated as a big single-line macro.

feat: introduce multi line macro in rpp 

---

README.md

We've migrated from Azure Pipelines to GitHub Actions / Workflows.

README: Switch build badge to GitHub Actions

---

.github/workflows/fsp-qemu.yml
src/mainboard/sifive/hifive/src/main.rs
src/soc/sifive/fu540/src/clock.rs
src/soc/sifive/fu540/src/ddr.rs
src/soc/sifive/fu540/src/lib.rs
src/soc/starfive/jh7100/src/clock.rs

This fixes https://github.com/oreboot/oreboot/issues/443 by getting QEMU up and running for the virt board.
We also remove the QEMU specific workarounds. The current QEMU workarounds don't work, so let's just remove them. The HiFive1 is an outdated board, not very well modelled on QEMU and is not being worked on. Instead of leaving in some old hacks let's just remove then and remove it from the CI.

Get QEMU tests up and running

---

Makefile
Makefile.inc

The location of target has changed; for all mainboards, target
is at $(TOP)/oreboot.

Makefiles: tweak them for the new layout

---

src/mainboard/sunxi/nezha/README.md
src/mainboard/sunxi/nezha/sbi/src/execute.rs
src/mainboard/sunxi/nezha/start.S
src/soc/src/sunxi/d1/gpio.rs

This adds a debug helper for `ecall` (handy!), a reference to the Linux 5.18 WIP branch for the D1, disables the special `MAEE` bit for it to work, and lights up the LED on the Lichee RV module.

Nezha / D1 next

---

src/mainboard/emulation/qemu-riscv/fixed-dtfs.dts

The oreboot binary was large enough to not fit into the flash info area as defined by the qemu-riscv `fixed-dtfs.dts` if the binary contained debug information. Only the release build did fit. As we have enough memory over, we can increase the flash and even create a bootable image for debug.

Fix qemu riscv dts

---

.cargo/config.toml
Cargo.toml
xtask/Cargo.toml
xtask/src/gdb_detect.rs
xtask/src/main.rs
xtask/src/sunxi/mod.rs
xtask/src/sunxi/nezha.rs
xtask/src/target.rs

This pull request is a successor to #555, it introduces the `xtask` building system into Oreboot project. The xtask system provides an easy way to build, flash and debug Oreboot with more host platforms (like Windows). The Makefile build system is still kept for compatibility.
To use `xtask` build system, you may execute the following commands:
* cargo make
* cargo flash
* cargo gdb
* cargo asm
... to build image, flash, debug or view assembly code on Oreboot platforms.
On each command, we change directory in `src/mainboard/<vendor>/<board>` or use `--mainboard` to decide which board we need to build to, `--variant` to choose the type of target board, and use `--release` to build under release profile. Parameter `--verbose` would print verbose output message to allow us to debug xtask …

Introduce the xtask building system

---

src/mainboard/sunxi/nezha/bt0/Cargo.toml
src/mainboard/sunxi/nezha/main/Cargo.toml

Seemingly, "commit" never worked. This explains the current broken build.
This also fixes cargo warning unused manifest key "commit".
Example warning:
```
warning: src/mainboard/sunxi/nezha/main/Cargo.toml: unused manifest key: dependencies.riscv.commit
warning: src/mainboard/sunxi/nezha/main/Cargo.toml: unused manifest key: dependencies.rustsbi.commit
```

Lock deps to fix build

---

rust-toolchain.toml

Update Rust toolchain to nightly-2022-10-12

---

src/mainboard/sunxi/nezha/bt0/src/main.rs

Run `cargo doc --all-features --document-private-items`
```
Documenting oreboot-nezha-bt0 v0.1.0 (./src/mainboard/sunxi/nezha/bt0)
warning: this URL is not a hyperlink
--> src/mainboard/sunxi/nezha/bt0/src/main.rs:250:5
|
250 | /// https://github.com/smaeul/u-boot/blob/55103cc657a4a84eabc9ae2dabfcab149b07934f/board/sunxi/board-riscv.c#L72-L75
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://github.com/smaeul/u-boot/blob/55103cc657a4a84eabc9ae2dabfcab149b07934f/board/sunxi/board-riscv.c#L72-L75>`
|
= note: bare URLs are not automatically turned into clickable links
= note: `#[warn(rustdoc::bare_urls)]` on by default
```

oreboot-nezha-bt0: rustdoc: clickable U-Boot link

---

src/mainboard/sunxi/nezha/README.md

From @orangecms in https://github.com/oreboot/oreboot/pull/615#discussion_r1008187193:
> More than just the DTS is needed, so the reference was to the branch.
> 
> How do you feel about keeping the phrasing as is, adding the Markdown link formatting, and giving the link a title that is the URL again, so it'll be rendered in Rust docs just like on GitHub? We could improve the wording thereafter.

docs: refactor nezha readme section Notes on Device Tree

---

.github/workflows/build.yml

* Add the yaml start of document marker
* Ignore "truthy" for "on" key
* Remove extra spaces in branches
* Fix indent all job steps

Lint github actions manifest

---

Makefile
rust-toolchain.toml

This removes toolchain installation from Makefile, which is automatically being handled by rust-toolchain.toml.

Rework toolchain setup

---

Makefile.inc

Use the same dprint tooling for 'fmt-ing' that we use in top level and CI.
----
```console
$ cd ${oreboot}/src/mainboard/emulation/qemu-riscv
$ time make checkformat 
***** Oreboot Build Config *****
TOP          = /home/ben/ofw/oreboot-cicd
MODE         = release
TARGET       = riscv64imac-unknown-none-elf
TARGET_DIR   = /home/ben/ofw/oreboot-cicd/target/riscv64imac-unknown-none-elf/release
TOOLS_TARGET = x86_64-unknown-linux-gnu
cargo --version  = cargo 1.66.0-nightly (3cdf1ab25 2022-10-07)
rustc --version  = rustc 1.66.0-nightly (db0597f56 2022-10-11)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.66.0-nightly (db0597f56 2022-10-11)`
rustup …
```

Makefiles: Use dprint in child make files

---

.github/workflows/build.yml

Upgrade checkout action to 'v3' (Node.js 16).
Fix deprecation of Node.js 12 (checkout@v2) in CI Actions.
> Node.js 12 actions are deprecated. For more information see:
> https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
See "Annotations" in https://github.com/oreboot/oreboot/actions/runs/3413485115
Fixes oreboot/oreboot#626

CI: Upgrade checkout actions to 'v3'

---

src/mainboard/sunxi/nezha/Makefile
src/mainboard/sunxi/nezha/bt0/src/main.rs
src/mainboard/sunxi/nezha/compression/Cargo.toml
src/mainboard/sunxi/nezha/compression/src/lib.rs
src/mainboard/sunxi/nezha/main/Cargo.toml
src/mainboard/sunxi/nezha/main/src/main.rs
xtask/src/main.rs
xtask/src/sunxi/nezha.rs

This expands the make targets in a manner I don't like _that_ much.
It works though, tried MnemOS and xv6:
```
make nosbiflashwithpayload \
PAYLOAD=~/firmware/Allwinner/D1/xv6-d1/kernel/kernel.bin
```
xv6 may have some assumptions not fulfilled by oreboot yet. At least it says it's booting up and echoes back keyboard input. MnemOS boots up fine.

sunxi/nezha: non-SBI support

---

src/mainboard/sunxi/nezha/bt0/Cargo.toml
src/mainboard/sunxi/nezha/bt0/src/main.rs
src/mainboard/sunxi/nezha/main/Cargo.toml
src/soc/Cargo.toml

* Upgrade so work in #636 is done against the most recent release of `d1-pac`. See https://github.com/duskmoon314/aw-pac/compare/d1-pac/v0.0.23...d1-pac/v0.0.30
* https://docs.rs/riscv/0.10.0/riscv/#critical-section-single-hart
See CI: https://github.com/oreboot/oreboot/actions/runs/3431521920/jobs/5719748900#step:4:226
```
error[E0599]: `Peripherals` is not an iterator
--> src/mainboard/sunxi/nezha/bt0/src/main.rs:422:26
|
422  |     let p = Peripherals::take().unwrap();
|                          ^^^^ `Peripherals` is not an iterator
|
:::
/home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/d1-pac-0.0.30/src/lib.rs:1749:1
|
1749 | pub struct Peripherals {
| ---------------------- doesn't satisfy `Peripherals: Iterator`
|
= note: the following trait bounds were not satisfied: …
```

[oreboot-soc] Upgrade d1-pac to v0.0.30

---

src/soc/src/lib.rs

Silence the warning that `int_abs_diff` has been included since Rust 1.60.0
`oreboot-soc` does not build with a `rustc` before 1.60.0 anyway, so removing this feature is safe
Signed off by: rmsyn <rmsynchls@gmail.com>

[oreboot-soc] remove feature(int_abs_diff)

---

src/mainboard/sunxi/nezha/bt0/src/main.rs

Silence the warning that `int_abs_diff` has been included since Rust 1.60.0
warning: the feature `int_abs_diff` has been stable since 1.60.0 and no longer requires an attribute to enable
--> src/mainboard/sunxi/nezha/bt0/src/main.rs:4:12

[oreboot-nezha-bt0] remove feature(int_abs_diff)

---

src/mainboard/sunxi/nezha/main/src/main.rs

Fix warning from rustc:
constant `PAYLOAD_OFFSET` is never used

[oreboot-nezha-main] Comment out Dead Code

---

.github/auto-merge.yml

Our "merge bot" (aka `probot-auto-merge`) is a GitHub App <https://github.com/apps/probot-auto-merge> which is no longer functional, operational, or maintained.
> Hosting for this project is unmaintained as there are alternatives using GitHub Actions.
bobvanderlinden/probot-auto-merge@3da1900ecebbfc9b80e1112d4157149279f6fcaa
Closes: oreboot/oreboot#653

[CI/CD] Remove `probot-auto-merge` config

---

rust-toolchain.toml

Update Rust toolchain to nightly-2022-12-15

---

src/lib/log/src/lib.rs

Huge kudos to @dancrossnyc for walking through this with us.
Less code, more safety, no global alloc - this turned out to be much nicer :)

lib/log: rework without global allocator

---

src/lib/log/Cargo.toml
src/lib/log/src/lib.rs

Dan Cross is right; the debug function does not need to come from here.
If one wanted, one could optionally add that to a specific
implementation.
Instead, add some handy functions for debugging here, to print values as
hex, pointers, etc.. They will help you e.g. when the memory map is
unclear and the print! macro would want to use absolute instead of
relative memory addresses. It helped me figure out the JH7110 SoC.
And because some platforms may not allow for using atomics in SRAM, make
the mutex in this crate opt-in.

lib/log: mutex and debug features, drop debug fn

---

src/mainboard/starfive/visionfive2/bt0/src/main.rs

Unwrap can be very dangerous in firmare; as code
evolves, we have found it can explode in unexpected ways.
Use let some instead.

visionfive2 main.rs: use let Some(), not unwrap

---

dprint.json

This is external code, so no point for us to check it with our rules. It currently raises an error in edk2, so ignore it.

dprint: ignore 3rdparty/

---

Makefile
dprint.json

- dprint needs an upgrade: https://github.com/dprint/dprint/issues/731
- remove stack-sizes; it is a library and cannot be installed as a binary

upgrade tooling

---

src/mainboard/emulation/qemu-riscv/link.ld
src/mainboard/emulation/qemu-riscv/src/main.rs

This patch set fixes a collection of bugs in the build process of qemu-riscv target. Even thought the qemu-riscv target builds and to some extent works, that souldn't have done, and the only reason it worked previously is sheer luck. The initial boot starter assembly blob was never used. In addition to that, The load address for the binary was not correct and some unnecessary symbols were forced to be kept which gave some linker error once we start doing anything remotely interesting in the rom.

[qemu-riscv] Build fix

---

.gitignore

Those files are created at random places in the repo every time I try to debug something using gdb + gef
Signed-off-by: Ahmed <ahmedsoliman@oddcoder.com>

Add .gdb_history file to list of git ignores

---

Documentation/boot-flow.md

as pointed out in https://github.com/oreboot/oreboot/pull/709#discussion_r1359776118

Documentation/boot-flow: fix link to RISC-V platform spec

---

src/mainboard/starfive/visionfive2/Makefile

Uses the supplied `PORT` Makefile variable as an argument to `vf2-loader`.

fixup: visionfive2: use Makefile `PORT` argument

---

.github/workflows/build.yml
dprint.json
rust-toolchain.toml
src/arch/src/lib.rs
src/arch/src/riscv64/sbi/execute.rs
src/arch/src/riscv64/sbi/runtime.rs
src/lib/log/src/lib.rs
src/mainboard/starfive/visionfive2/bt0/src/main.rs
src/mainboard/sunxi/nezha/main/src/main.rs

Drop the Arm and PPC toolchains for now. They are not used and only waste space at this point.

Upgrade Rust to nightly-2024-01-10

---

src/mainboard/starfive/visionfive2/bt0/Cargo.toml
src/mainboard/starfive/visionfive2/bt0/src/dram.rs
src/mainboard/starfive/visionfive2/bt0/src/init.rs
src/mainboard/starfive/visionfive2/bt0/src/main.rs
src/mainboard/starfive/visionfive2/bt0/src/pac.rs
src/mainboard/starfive/visionfive2/bt0/src/pll.rs
src/mainboard/starfive/visionfive2/bt0/src/uart.rs

Uses the [`jh71xx-pac`](https://github.com/rmsyn/jh71xx-pac) library for peripheral access in the `Visionfive2` mainboard.

feature: VisionFive2 PAC for peripheral access

---

src/lib/log/Cargo.toml
src/lib/log/src/lib.rs
src/mainboard/starfive/visionfive2/bt0/Cargo.toml
src/mainboard/starfive/visionfive2/bt0/build.rs
src/mainboard/starfive/visionfive2/bt0/src/main.rs
src/mainboard/starfive/visionfive2/bt0/src/pac.rs
src/mainboard/starfive/visionfive2/bt0/src/uart.rs
src/mainboard/starfive/visionfive2/main/Cargo.toml
src/mainboard/sunxi/nezha/bt0/Cargo.toml
src/mainboard/sunxi/nezha/main/Cargo.toml
src/soc/src/sunxi/d1/gpio.rs

Uses the [`jh71xx-hal`](https://github.com/rmsyn/jh71xx-hal) crate for peripheral access, mainly the `UART0` peripheral.
The `jh71xx-hal` is currently a work-in-progress. Most notably, the `interrupt` code around `PLIC` configuration is apparently broken. The GPIO code also requires a big rewrite to match code from other `embedded-hal` implementations.
Depends on the changes in https://github.com/oreboot/oreboot/pull/713

feature: visionfive2: use `jh71xx-hal` for peripheral access

---

src/mainboard/starfive/visionfive1/bt0/.cargo/config.toml
src/mainboard/starfive/visionfive1/bt0/src/main.rs
src/mainboard/starfive/visionfive1/main/.cargo/config.toml
src/mainboard/starfive/visionfive1/main/src/main.rs
src/mainboard/starfive/visionfive2/bt0/.cargo/config.toml
src/mainboard/starfive/visionfive2/bt0/src/main.rs
src/mainboard/starfive/visionfive2/main/.cargo/config.toml
src/mainboard/starfive/visionfive2/main/src/main.rs
src/mainboard/sunxi/nezha/bt0/.cargo/config.toml
src/mainboard/sunxi/nezha/bt0/build.rs
src/mainboard/sunxi/nezha/bt0/src/main.rs
src/mainboard/sunxi/nezha/main/.cargo/config.toml

add riscv debuginfo for easier debugging and rename elf entrypoint _start to match ENTRY in linker script

fixup: add riscv debuginfo and entrpoint for objdump

---

Makefile

While trying to run `make firsttime`, it turns out clap_lex requires rust 1.74:
$ make firsttime
rustup run --install 1.73 cargo install --version 0.3.6 cargo-binutils
Ignored package `cargo-binutils v0.3.6` is already installed, use --force to override
rustup run --install 1.73 cargo install --version 0.27.1 cargo-tarpaulin
Updating crates.io index
Installing cargo-tarpaulin v0.27.1
Updating crates.io index
error: failed to compile `cargo-tarpaulin v0.27.1`, intermediate artifacts can be found at `/tmp/cargo-install7v3Pgi`. To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
package `clap_lex v0.7.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.73.0
Try …

Bump rust version to 1.74

---

Cargo.toml

This silences the warning:
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`

Add an explicit resolver to the workspace

---

xtask/src/starfive/visionfive2.rs

No functional changes, merely correcting build warnings.

xtask: starfive: silence visionfive2 warnings

---

src/mainboard/starfive/visionfive2/bt0/src/ddr_start.rs
src/mainboard/starfive/visionfive2/bt0/src/ddrcsr.rs
src/mainboard/starfive/visionfive2/bt0/src/ddrphy.rs
src/mainboard/starfive/visionfive2/bt0/src/dram.rs

Uses the `jh71xx-pac` library for DDR configuration in the VisionFive2 mainboard.

feature: vf2: use `jh71xx-pac` for DDR configuration

---

Makefile

make can change directory prior to running a target. Let's make use of that feature instead of relying on the cd utility.

Makefile: don't rely on cd

---

src/lib/compression/src/lib.rs
src/lib/layoutflash/src/areas.rs
xtask/src/main.rs
xtask/src/starfive/visionfive1.rs
xtask/src/starfive/visionfive2.rs
xtask/src/sunxi/nezha.rs
xtask/src/util.rs

No functional changes, merely fixing `cargo clippy` warnings.

Fix clippy warnings across the project

---

xtask/src/starfive/visionfive2.rs
xtask/src/starfive/visionfive2_hdr.rs

The struct is based on what the original vendor tool does. No clue yet how the secure boot flow or setup really works. Reference: https://github.com/starfive-tech/Tools/issues/8
Add a Default impl.
Use CRC_32_ISO_HDLC from the crc crate as figured out by https://github.com/jonirrings/vf2-header :)

xtask/starfive/visionfive2: rework header creation

---

Makefile
src/arch/src/lib.rs
src/arch/src/riscv64/sbi/runtime.rs

The computation at runtime turned out to not work in practice.

arch/riscv: ensure alignment via repr() directive

---

src/mainboard/sunxi/nezha/bt0/build.rs
src/mainboard/sunxi/nezha/bt0/src/main.rs

The KEEP linker directive does not prohibit the rust compiler to garbage collect code, unless #[used] is used. Therefore remove MainStageHead as it's effectively not there.
The first jump instruction did assume MainStageHead was there and therefore skipped the first 2 instructions of _start. This is now fixed.
This changes the first instruction to be in assembly rather than inline assembly as the rust compiler seems to like to pad the instruction with unimp.
This means that disabling interrupts and enabling "theadisaee" and "maee" is now correctly done.

nezha: Fix first jump

---

xtask/src/gdb_detect.rs
xtask/src/util.rs

- When returning a path, prefer using `&'static Path` instead of `PathBuf` when heap allocation is unnecessary.

refactor: return &'static Path when returning PathBuf is unnecessary

---

Cargo.toml

This makes it simpler to new boards, stages, and libraries.

Cargo.toml: use * to include all boards and lib crates

---

Makefile

upgrading the rustc version to latest stable 1.85.0 to solve dependency issues. 
solving #771

makefile: upgrade rustc version to latest stable

---

.github/workflows/build.yml
Makefile
Makefile.inc
src/console/Makefile
src/lib/consts/Makefile
src/lib/util/Makefile

most of the code is non-testable so as per the discussion in the issue #771 we are removing it.
also removed the `coverage` target from Makefiles

makefile: remove tarpaulin integration

---

Cargo.lock
src/arch/src/riscv64/mod.rs
src/mainboard/sunxi/nezha/bt0/src/main.rs
src/mainboard/sunxi/nezha/main/Cargo.toml
src/mainboard/sunxi/nezha/main/src/main.rs
src/mainboard/sunxi/nezha/main/src/sbi_platform.rs
src/soc/src/sunxi/d1/clint.rs

This is in preparation of #772; the current only SoC we use our compression library for is the D1, so that's to be switched, and as it turns out, we had some breakage - and could already benefit  from our newly introduced XuanTie library.

sunxi/nezha fixes + rework

---

src/mainboard/canaan/canmv-k230/bt0/src/main.rs
src/mainboard/canaan/canmv-k230/main/src/main.rs
src/mainboard/rockchip/rk3566/bt0/src/main.rs
src/mainboard/starfive/visionfive1/bt0/src/main.rs
src/mainboard/starfive/visionfive2/bt0/src/main.rs
src/mainboard/sunxi/nezha/bt0/src/main.rs

The former has been deprecated.
See https://doc.rust-lang.org/std/intrinsics/fn.transmute.html

use mem::transmute instead of intrinsics::transmute

---

src/mainboard/starfive/visionfive2/bt0/Cargo.toml

Cargo would now warn on features it doesn't know.
Instead of just declaring what features can take what values, they have to be listed in the `lints.rust` config section. See also: https://blog.rust-lang.org/2024/05/06/check-cfg/

starfive/visionfive2/bt0: configure cfg lints

---

xtask/src/main.rs

The help texts got in the wrong place, and noone noticed. Whoops!

xtask: fix clap annotations
